{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "@pytest.mark.run(order=2)\n    def test_one():\n>       assert True == False\nE       assert True == False\n\ntest_demo.py:12: AssertionError"}, "attachments": [{"name": "log", "source": "15d5a8fa-8a59-441b-998b-14dd543e542c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "7e592f35-09d7-43ed-ab68-1a7d1694c25a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d6d26aa5-508e-4740-9ef1-2a30deab57e5-attachment.txt", "type": "text/plain"}], "start": 1564493501616, "stop": 1564493501616, "uuid": "db698058-6eda-4140-94c7-723b2544c384", "historyId": "1f7492fb48f8fc013720c6604b5c3181", "fullName": "test_demo#test_one", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "anxiaodongdeMacBook-Pro.local"}, {"name": "thread", "value": "84097-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}